language: python
sudo: required

matrix:
  include:
    - dist: bionic
      python: 3.7
      env: dist="18.04 LTS bionic"

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}

virtualenv:
        system_site_packages: false

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq vlan
  - sudo DEBIAN_FRONTEND=noninteractive apt-get -y install ansible libffi-dev libssl-dev
  - cd ansible

# bare metal installation
install:
  - travis_wait 60 sudo ansible-playbook -i "localhost," -c local install.yml

before_script:
  - cd ..
# run tests
script:
  # run unit tests (bare metal)
  - travis_wait 60 sudo py.test -v mininet/test/
  # build ubuntu-based isula container
  - travis_wait 60 isula build -t containernet/containernet:ubuntu .
  # run unit tests on ubuntu:xenial-based isula container
  - isula run --name containernet -i --rm --privileged --pid='host' -v /var/run/isula.sock:/var/run/isula.sock containernet/containernet:ubuntu py.test -v mininet/test/
  # build centos-based isula container
  - travis_wait 60 isula build -t containernet/containernet:centos7 -f Dockerfile.centos .
  # run unit tests on centos7-based isula container
  - isula run --name containernet -i --rm --privileged --pid='host' -v /var/run/isula.sock:/var/run/isula.sock containernet/containernet:centos7 py.test -v mininet/test/

notifications:
  email:
    on_success: change
    on_failure: always
